name: package

on:
  push:
    tags:
      - 'v*.*.*'

jobs:
  package:
    runs-on: ubuntu-latest

    steps:
      - name: checkout
        uses: actions/checkout@v3
      - name: setup node
        uses: actions/setup-node@v3
        with:
          node-version: 16
      - name: setup npm
        run: |
          yarn install --network-concurrency 1 --network-timeout 1000
          yarn upgrade
      - name: setup npmrc
        run: echo "//registry.npmjs.org/:_authToken=${NPM_TOKEN}" > ~/.npmrc
        env:
          NPM_TOKEN: ${{ secrets.CC_NPM_MANAGER_TOKEN }}
      - name: publish
        run: npm publish --access public
