name: package

on:
  push:
    tags:
      - 'v*.*.*'

jobs:
  package:
    runs-on: ubuntu-latest

    steps:
      - name: checkout
        uses: actions/checkout@v2
      - name: setup node
        uses: actions/setup-node@v2
        with:
          node-version: '14.x'
      - name: setup npm
        run: yarn
      - name: package
        run: npm pack
      - name: publish
        run: npm publish
        env:
          NODE_AUTH_TOKEN: ${{ secrets.CC_NPM_MANAGER_TOKEN }}
